esphome:
  name: bedroom_unit
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "UPCB7751E2"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.122
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1


logger:

api:

ota:

binary_sensor:
  - platform: gpio
    pin: D5
    name: "PIR Sensor"
    device_class: motion
