substitutions:
  node_name: cam_01

esphome:
  platform: ESP32
  board: esp32cam

packages:
  node_base: !include common/node_base.yaml

wifi:
  manual_ip:
    static_ip: 192.168.0.122

time:
  - platform: sntp
    id: sntp_time

output:
  - platform: gpio
    pin: GPIO4
    id: light_gpio

binary_sensor:
  - platform: gpio
    pin: GPIO2
    name: ${node_name} motion sensor
    device_class: motion

switch:
  - platform: restart
    name: ${node_name} restart

light:
  - platform: binary
    output: light_gpio
    name: ${node_name} light

esp32_camera:
  name: ${node_name} camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1024x768
  max_framerate: 5 fps
