substitutions:
  node_name: diplay_test

esphome:
  platform: ESP8266
  board: d1_mini

packages:
  node_base: !include common/node_base.yaml

wifi:
  manual_ip:
    static_ip: 192.168.0.130

font:
  - file: common/arial.ttf
    id: font1
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    id: screen
    brightness: 10%
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");

switch:
  - platform: template
    name: "$unit_name brightness"
    optimistic: true
    turn_on_action:
      - lambda: |-
          id(screen).turn_on();
    turn_off_action:
      - lambda: |-
          id(screen).turn_off();
