substitutions:
  unit_name: test

esphome:
  name: test_unit
  platform: ESP8266
  board: d1_mini

wifi:
  power_save_mode: HIGH
  fast_connect: on
  ssid: "UPCB7751E2"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.130
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1

logger:

api:

ota:

web_server:

i2c:

font:
  - file: 'Arial.ttf'
    id: font1
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    id: screen
    brightness: 10%
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");

switch:
  - platform: template
    name: "$unit_name brightness"
    optimistic: true
    turn_on_action:
      - lambda: |-
          id(screen).turn_on();
    turn_off_action:
      - lambda: |-
          id(screen).turn_off();
