substitutions:
  unit_name: Greenhouse

esphome:
  name: greenhouse_env_unit
  platform: ESP8266
  board: d1_mini
  on_boot:
    - wait_until:
        api.connected:
    - logger.log: "API is connected!"
    - deep_sleep.prevent: deep_sleep_1
    - delay: 15s
    - logger.log: "Going deep sleep"
    - deep_sleep.enter: deep_sleep_1


wifi:
  power_save_mode: HIGH
  fast_connect: on
  ssid: "UPCB7751E2"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.123
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1

deep_sleep:
  id: deep_sleep_1
  run_duration: 2min
  sleep_duration: 20min

logger:

api:

ota:

i2c:

sensor:
  - platform: bme280
    temperature:
      name: "$unit_name Temperature"
      oversampling: 4x
    humidity:
      name: "$unit_name Humidity"
    address: 0x76
    update_interval: 10s
  - platform: adc
    pin: A0
    name: "$unit_name Battery"
    icon: mdi:battery
    update_interval: 10s
    filters:
      - multiply: 4
  - platform: uptime
    name: "$unit_name Uptime"
    update_interval: 10s
