substitutions:
  node_name: plant-waterer

esphome:
  platform: ESP8266
  board: d1_mini

packages:
  node_base: !include common/node_base.yaml

wifi:
  manual_ip:
    static_ip: 192.168.1.121

output:
  # motor controls
  - platform: gpio
    id: direction_pin0_m1
    pin: D5
  - platform: gpio
    id: direction_pin1_m1
    pin: D6
  - platform: esp8266_pwm
    pin: D7
    id: speed_pin_m1

switch:
  - platform: template
    id: run_pump
    name: '${node_name} run five min'
    optimistic: true
    turn_on_action:
      - script.execute: run_pump_for_five_min
    turn_off_action:
      - script.stop: run_pump_for_five_min

  # pump control
  - platform: template
    id: switch_pump
    name: '${node_name} pump'
    optimistic: true
    turn_on_action:
      - script.execute: start_pump
    turn_off_action:
      - script.execute: stop_pump

script:
  - id: start_pump
    then:
      - output.turn_on: direction_pin1_m1
      - output.turn_off: direction_pin0_m1
      - output.set_level:
          id: speed_pin_m1
          level: 100%
      - delay: 0.1s
      - output.set_level:
          id: speed_pin_m1
          level: 65%

  - id: stop_pump
    then:
      - output.turn_off: direction_pin1_m1
      - output.turn_off: direction_pin0_m1
      - output.set_level:
          id: speed_pin_m1
          level: 0

  - id: run_pump_for_five_min
    then:
      - switch.turn_on: switch_pump
      - delay: 5min
      - switch.turn_off: switch_pump