esphome:
  name: plant_unit
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "UPCB7751E2"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.121
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1

logger:

web_server:

api:

ota:

script:
  - id: start_pump
    then:
      - output.turn_on: direction_pin0_e1
      - output.turn_off: direction_pin1_e1
      - output.set_level:
          id: speed_pin_e1
          level: 100%
  - id: stop_pump
    then:
      - output.set_level:
          id: speed_pin_e1
          level: 0

output:
  - platform: esp8266_pwm
    pin: D5
    id: speed_pin_e1
  - platform: gpio
    pin: D6
    id: direction_pin0_e1
  - platform: gpio
    pin: D7
    id: direction_pin1_e1

switch:
  - platform: template
    name: "Pump"
    optimistic: true
    turn_on_action:
      - script.execute: start_pump
      - delay: 0.1s
      - output.set_level:
          id: speed_pin_e1
          level: 60%
    turn_off_action:
      - script.execute: stop_pump

  - platform: gpio
    name: "Valve 1"
    pin:
      number: D3
      inverted: true
  - platform: gpio
    name: "Valve 2"
    pin:
      number: D2
      inverted: true
