substitutions:
  node_name: esp32-cam

esphome:
  platform: ESP32
  board: esp32cam

packages:
  node_base: !include common/node_base.yaml

wifi:
  manual_ip:
    static_ip: 192.168.0.122

output:
  - platform: gpio
    pin: GPIO4
    id: light_gpio

light:
  - platform: binary
    output: light_gpio
    name: ${node_name} light

esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
