substitutions:
  unit_name: test

esphome:
  name: test_unit
  platform: ESP8266
  board: d1_mini
  includes:
    - custom_components/nrf24l01_transmitter.h
  libraries:
    - "RF24"

wifi:
  power_save_mode: HIGH
  fast_connect: on
  ssid: "UPCB7751E2"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.130
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1

logger:

api:

ota:

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new NRF24L01Sensor();
      App.register_component(my_sensor);
      return {my_sensor};

    sensors:
      name: "$unit_name My Custom Sensor"
