esphome:
  name: wshome
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "UPCB7751E2"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:

time:
  - platform: homeassistant
    id: hatime

font:
  - file: 'Arial.ttf'
    id: font1
    size: 14

switch:
  - platform: template
    name: "Backlight"
    turn_on_action:
      then:
        - lambda: |-
            id(screen).backlight();
    turn_off_action:
      then:
        - lambda: |-
            id(screen).no_backlight();

sensor:
  - platform: bme680
    temperature:
      id: temperature
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      id: pressure
      name: "BME680 Pressure"
    humidity:
      id: humidity
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    address: 0x77
    update_interval: 60s

  - platform: adc
    pin: A0
    name: "TEMT6000 Illuminance"
    unit_of_measurement: lx
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

display:
  - platform: lcd_pcf8574
    id: screen
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.strftime(0, 0, "%d.%m   %H:%M:%S", id(hatime).now());
      it.printf(0, 1, "%.1ft %.0f%% %.1f", id(temperature).state, id(humidity).state, id(pressure).state);
