substitutions:
  node_name: cam-esp

esphome:
  platform: ESP32
  board: esp32cam

packages:
  node_base: !include ../common/node_base.yaml

wifi:
  manual_ip:
    static_ip: 192.168.1.122

deep_sleep:
  id: deep_sleep_1

time:
  - platform: sntp
    id: sntp_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 20
        then:
          - script.execute: go_sleep

binary_sensor:
  - platform: gpio
    pin: GPIO2
    name: ${node_name} motion sensor
    device_class: motion

button:
  - platform: restart
    id: restart_btn

  - platform: template
    name: ${node_name} go sleep
    on_press:
      - script.execute: go_sleep

esp32_camera:
  name: ${node_name} camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1024x768
  max_framerate: 2fps


script:
  - id: go_sleep
    then:
      - deep_sleep.enter:
          id: deep_sleep_1
          until: '8:00:00'
          time_id: sntp_time