esphome:
  name: ${node_name}-node
  build_path: ../build/${node_name}

wifi:
  power_save_mode: HIGH
  fast_connect: on
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # <static_ip: 0.0.0.0> add in your configuration
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1


logger:

web_server:

api:

ota:

i2c:

