esphome:
  name: ${node_name}-node
  build_path: ../build/${node_name}

wifi:
  fast_connect: on
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # <static_ip: 0.0.0.0> add in your configuration
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8


logger:

web_server:

# ota:

i2c:

