substitutions:
  node_name: cam_two

packages:
  node_base: !include ../common/node_base.yaml

esphome:
  platform: ESP32
  board: m5stack-timer-cam
  platformio_options:
    upload_speed: 115200
  on_boot:
    then:
      pcf85063.read_time:

wifi:
  manual_ip:
    static_ip: 192.168.1.123

i2c:
  - id: rtc_bus
    scl: GPIO14
    sda: GPIO12

mqtt:
  id: mqtt_client
  broker: 192.168.1.105

time:
  - platform: pcf85063
    id: pcf85063_time
    update_interval: never
  - platform: sntp
    id: sntp_time
    on_time_sync:
      then:
        pcf85063.write_time:

binary_sensor:
  - platform: gpio
    name: button
    pin:
      number: GPIO37
      inverted: true
    device_class: connectivity

sensor:
  - platform: adc
    name: 'Battery Voltage'
    pin: GPIO38
    filters:
      multiply: 3.3

output:
  - platform: gpio
    id: led_output
    pin: GPIO2

light:
  - platform: binary
    name: led
    output: led_output

switch:
  - platform: gpio
    pin: GPIO33
    name: 'Battery On'

esp32_camera: !include ./esp32_camera.yaml